import { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, FileText, MapPinned } from 'lucide-react';
import { MapContainer, Polygon, Polyline, Popup, TileLayer } from 'react-leaflet';
import type { Case, Project } from '../types';

export const mapColors: Record<string, string> = { Completed: '#16a34a', 'In Progress': '#eab308', Delayed: '#dc2626', 'At Risk': '#f97316', 'Under Review': '#2563eb' };
const statusClass: Record<string, string> = { 'In Progress': 'status-blue', 'Under Review': 'status-purple', Completed: 'status-green', Delayed: 'status-red', 'At Risk': 'status-orange', 'Compensation Pending': 'status-yellow' };
export function StatusBadge({ status }: { status: string }) { return <span className={`status-badge ${statusClass[status] || 'status-blue'}`}><i />{status}</span>; }
export function ProgressBar({ value }: { value: number }) { return <div className="progress-line"><span style={{ width: `${value}%` }} /></div>; }
export function PageHeader({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) { return <div className="page-heading compact"><div><div className="eyebrow">WORKSPACE</div><h1>{title}</h1><p>{description}</p></div>{action && onAction && <button type="button" className="button button-primary" onClick={onAction}><span>＋</span>{action}</button>}</div>; }
export function MiniStat({ label, value, detail, icon }: { label: string; value: string; detail: string; icon?: ReactNode }) { return <div className="mini-stat"><div className="mini-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
export function EmptyState({ text }: { text: string }) { return <div className="empty-state"><FileText size={21} /><span>{text}</span></div>; }
export function MapPanel({ center, polygons = [], line }: { center: [number, number]; polygons?: [number, number][][]; line?: [number, number][] }) { return <div className="map-container"><MapContainer center={center} zoom={12} scrollWheelZoom={false} zoomControl={false} style={{ height: '100%', width: '100%' }}><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{line && <Polyline positions={line} pathOptions={{ color: '#2541b2', weight: 4, dashArray: '8 8' }} />}{polygons.map((polygon, index) => <Polygon key={index} positions={polygon} pathOptions={{ color: '#f59e0b', fillColor: '#fbbf24', fillOpacity: .35, weight: 2 }}><Popup><strong>Selected parcel</strong><br />Demo geometry · preserved cadastral source</Popup></Polygon>)}</MapContainer><div className="map-overlay"><span><i className="map-legend green" /> Completed</span><span><i className="map-legend yellow" /> In progress</span><span><i className="map-legend red" /> Delayed</span></div></div>; }
export function ProjectLink({ project }: { project: Project }) { return <Link to={`/projects/${project.id}`} className="table-title">{project.name}<span className="table-sub">{project.projectId} · {project.type}</span><ArrowUpRight size={13} /></Link>; }
export function CaseLink({ item }: { item: Case }) { return <Link to={`/cases/${item.id}`} className="table-title mono">{item.caseId}<span className="table-sub">{item.parcelId} · Survey {item.surveyNumber}</span></Link>; }
export function MapPinIcon() { return <MapPinned size={17} />; }
